version: 2.1

orbs:
  # my custom (mock) Terraform Orb inline
  terraform:
    description: mock inline Orb
    commands:
      lint:
        description: mock lint
        parameters:
          exit-code:
            type: integer
            default: 2
        steps:
          - run:
              name: Lint Terraform files
              command: |
                mark_as_success() {
                  rv=$?
                  # do not fail if last command exited 2
                  if [ $rv -eq 2 ]; then
                    echo "last command exited 2; marking this green!"
                    exit 0
                  else
                    exit $rv
                  fi
                }

                trap mark_as_success EXIT

                tflint() {
                  echo "mock TFlint.."
                  exit << parameters.exit-code >>
                }

                # run TFlint...
                tflint

executors:
  base:
    docker:
      - image: hashicorp/terraform:<< parameters.tag >>
    parameters:
      tag:
        default: 1.3.7
        description: Specify the Terraform Docker image tag for the executor
        type: string

jobs:
  test:
    executor: base
    parameters:
      tflint-exit-code:
        type: integer
    steps:
      - terraform/lint:
          exit-code: << parameters.tflint-exit-code >>
      - run:
          name: Post-lint command
          command: echo "next step!"     

workflows:
  main:
    jobs:
      - test:
          matrix:
            parameters:
              tflint-exit-code:
                # should pass, with next step(s) continued
                - 2
                # should fail on terraform/lint step then
                - 1
                # should pass, with next step(s) continued
                - 0

# VS Code Extension Version: 1.5.1
